[tool.poetry]
name = "bank_project"
version = "0.1.0"
description = "A project for processing bank transactions with support for JSON, CSV, and XLSX formats."
authors = ["Your Name <your.email@example.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^5.0.0"
flake8 = "^7.1.1"
isort = "^5.13.2"
mypy = "^1.11.2"
pandas-stubs = "^2.2.2.240603"
types-requests = "^2.32.0"  # Исправленная версия

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.report]
exclude_also = [
    'def __repr__',
    'if self.debug:',
    'if settings.DEBUG',
    'raise AssertionError',
    'raise NotImplementedError',
    'if 0:',
    'if __name__ == .__main__.:',
    'if TYPE_CHECKING:',
    'class .*\bProtocol\):',
    '@(abc\.)?abstractmethod',
]